name: .NET

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Publish .NET Core Project
      run: dotnet publish lwa.csproj -c Release -o release --nologo
      
    - name: base href
      run: sed -i 's/<base href="\/"\/>/<base href="\/law\/"\/>/g' release/wwwroot/index.html
    
    - name: .nojekyll
      run: touch release/wwwroot/.nojekyll
      
    - name: 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
          branch: gh-pages
          folder: release/wwwroot
